// Generated by Selenium IDE
package Tests;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.*;

public class SeleniumTests {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  //Programming button navigation
  @Test
  public void Programming() {
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("li:nth-child(1) > .directions__list-link > span")).click();
    vars.put("win3678", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3678").toString());
    String expectedUrl = "https://skillfactory.ru/courses/programmirovanie";
    String currentUrl = driver.getCurrentUrl();
    assertTrue("После клика страница должна открыться с URL: " + expectedUrl, currentUrl.contains(expectedUrl));
    driver.close();
  }

  //Analytics button navigation
  @Test
    public void AnalyticData() {
      driver.get("https://skillfactory.ru/");
      driver.manage().window().setSize(new Dimension(1936, 1048));
      vars.put("window_handles", driver.getWindowHandles());
      driver.findElement(By.cssSelector("li:nth-child(3) > .directions__list-link > span")).click();
      vars.put("win2541", waitForWindow(2000));
      driver.switchTo().window(vars.get("win2541").toString());
      String expectedUrl = "https://skillfactory.ru/courses/analitika-dannyh";
      String currentUrl = driver.getCurrentUrl();
      assertTrue("После клика страница должна открыться с URL: " + expectedUrl, currentUrl.contains(expectedUrl));
    driver.close();
    }

  //Free button navigation
  @Test
    public void Free() {
      driver.get("https://skillfactory.ru/");
      driver.manage().window().setSize(new Dimension(1936, 1048));
      vars.put("window_handles", driver.getWindowHandles());
      driver.findElement(By.linkText("БЕСПЛАТНО")).click();
      vars.put("win1403", waitForWindow(2000));
      driver.switchTo().window(vars.get("win1403").toString());
      String expectedUrl = "https://skillfactory.ru/free-events";
      String currentUrl = driver.getCurrentUrl();
      assertTrue("После клика страница должна открыться с URL: " + expectedUrl, currentUrl.contains(expectedUrl));
    driver.close();
    }

  //Corporate button navigation
  @Test
  public void Corporat() {
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("li:nth-child(6) > .main__nav-item")).click();
    vars.put("win1163", waitForWindow(2000));
    driver.switchTo().window(vars.get("win1163").toString());
    String expectedUrlPart = "/corporativnoye-obuchenye";
    String currentUrl = driver.getCurrentUrl();
    System.out.println("Current URL: " + currentUrl);
    assertTrue("URL должен содержать основную часть: " + expectedUrlPart, currentUrl.contains(expectedUrlPart));
    driver.close();
  }


  //All curses button navigation
  @Test
      public void Allcurses() {
        driver.get("https://skillfactory.ru/");
        driver.manage().window().setSize(new Dimension(1936, 1048));
        WebElement element = driver.findElement(By.cssSelector(".directions__list-link_green > span"));
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", element);
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.cssSelector(".directions__list-link_green > span")).click();
        vars.put("win3362", waitForWindow(2000));
        driver.switchTo().window(vars.get("win3362").toString());
        String expectedUrl = "https://skillfactory.ru/courses";
        String currentUrl = driver.getCurrentUrl();
        assertTrue("После клика страница должна открыться с URL: " + expectedUrl, currentUrl.contains(expectedUrl));
    driver.close();
    }

  //Data Science button navigation
  @Test
    public void DataScience() {
      driver.get("https://skillfactory.ru/");
      driver.manage().window().setSize(new Dimension(1936, 1048));
      vars.put("window_handles", driver.getWindowHandles());
      driver.findElement(By.cssSelector("li:nth-child(2) > .directions__list-link > span")).click();
      vars.put("win8279", waitForWindow(2000));
      driver.switchTo().window(vars.get("win8279").toString());
      String expectedUrl = "https://skillfactory.ru/courses/data-science";
      String currentUrl = driver.getCurrentUrl();
      assertTrue("После клика страница должна открыться с URL: " + expectedUrl, currentUrl.contains(expectedUrl));
    driver.close();
    }

  //Design button navigation
  @Test
    public void Design() {
      driver.get("https://skillfactory.ru/");
      driver.manage().window().setSize(new Dimension(1936, 1048));
      vars.put("window_handles", driver.getWindowHandles());
      driver.findElement(By.cssSelector("li:nth-child(6) > .directions__list-link > span")).click();
      vars.put("win307", waitForWindow(2000));
      driver.switchTo().window(vars.get("win307").toString());
      String expectedUrl = "https://skillfactory.ru/courses/design";
      String currentUrl = driver.getCurrentUrl();
      assertTrue("После клика страница должна открыться с URL: " + expectedUrl, currentUrl.contains(expectedUrl));
    driver.close();
    }

    //Higher education button navigation
    @Test
    public void Highereducation() {
      driver.get("https://skillfactory.ru/");
      driver.manage().window().setSize(new Dimension(1936, 1048));
      vars.put("window_handles", driver.getWindowHandles());
      driver.findElement(By.cssSelector("li:nth-child(5) > .directions__list-link > span")).click();
      vars.put("win9829", waitForWindow(2000));
      driver.switchTo().window(vars.get("win9829").toString());
      String expectedUrlPart = "https://new.skillfactory.ru/";
      String currentUrl = driver.getCurrentUrl();
      assertTrue("После клика страница должна открыться с URL: " + expectedUrlPart, currentUrl.contains(expectedUrlPart));
      driver.close();
    }

    //Contacts button navigation
    @Test
    public void Contacts() {
      driver.get("https://skillfactory.ru/");
      driver.manage().window().setSize(new Dimension(1936, 1048));
      vars.put("window_handles", driver.getWindowHandles());
      driver.findElement(By.cssSelector("li:nth-child(4) > .main__nav-item")).click();
      vars.put("win3404", waitForWindow(2000));
      driver.switchTo().window(vars.get("win3404").toString());
      String expectedUrl = "https://skillfactory.ru/contacts";
      String currentUrl = driver.getCurrentUrl();
      assertTrue("После клика страница должна открыться с URL: " + expectedUrl, currentUrl.contains(expectedUrl));
      driver.close();
    }

    //Media button navigation
    @Test
    public void Media() {
      driver.get("https://skillfactory.ru/");
      driver.manage().window().setSize(new Dimension(1936, 1048));
      vars.put("window_handles", driver.getWindowHandles());
      driver.findElement(By.cssSelector("li:nth-child(5) > .main__nav-item")).click();
      vars.put("win6562", waitForWindow(2000));
      driver.switchTo().window(vars.get("win6562").toString());
      String expectedUrlPart = "https://blog.skillfactory.ru/";
      String currentUrl = driver.getCurrentUrl();
      assertTrue("После клика страница должна открыться с URL: " + expectedUrlPart, currentUrl.contains(expectedUrlPart));
      driver.close();
    }

  //Management button navigation
    @Test
      public void Management() {
        driver.get("https://skillfactory.ru/");
        driver.manage().window().setSize(new Dimension(1936, 1048));
        WebElement element = driver.findElement(By.cssSelector(".directions__list-link_green > span"));
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", element);
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.cssSelector("li:nth-child(7) > .directions__list-link > span")).click();
        vars.put("win1372", waitForWindow(2000));
        driver.switchTo().window(vars.get("win1372").toString());
        String expectedUrl = "https://skillfactory.ru/courses/management-i-upravlenie";
        String currentUrl = driver.getCurrentUrl();
        assertTrue("После клика страница должна открыться с URL: " + expectedUrl, currentUrl.contains(expectedUrl));
      driver.close();
      }

  //Practice button navigation
    @Test
    public void Practice() {
      driver.get("https://skillfactory.ru/");
      driver.manage().window().setSize(new Dimension(1936, 1048));
      vars.put("window_handles", driver.getWindowHandles());
      driver.findElement(By.cssSelector("li:nth-child(3) > .main__nav-item")).click();
      vars.put("win4039", waitForWindow(2000));
      driver.switchTo().window(vars.get("win4039").toString());
      String expectedUrl = "https://skillfactory.ru/factory";
      String currentUrl = driver.getCurrentUrl();
      assertTrue("После клика страница должна открыться с URL: " + expectedUrl, currentUrl.contains(expectedUrl));
      driver.close();
    }

  //Tester button navigation
    @Test
    public void Tester() {
      driver.get("https://skillfactory.ru/");
      driver.manage().window().setSize(new Dimension(1936, 1048));
      vars.put("window_handles", driver.getWindowHandles());
      driver.findElement(By.cssSelector("li:nth-child(4) > .directions__list-link > span")).click();
      vars.put("win8739", waitForWindow(2000));
      driver.switchTo().window(vars.get("win8739").toString());
      String expectedUrl = "https://skillfactory.ru/courses/testirovanie";
      String currentUrl = driver.getCurrentUrl();
      assertTrue("После клика страница должна открыться с URL: " + expectedUrl, currentUrl.contains(expectedUrl));
      driver.close();
    }


  @After
  public void tearDown() {
    driver.quit();
  }
}
